<?php
/**
 * Sample tour packages shown on the homepage and /packages/index.php.
 * Each 'slug' must match a file in /packages/{slug}.php, which renders
 * through includes/package-template.php.
 */

$packages = [
    [
        'slug'        => 'kuala-lumpur-city-escape',
        'title_en'    => 'Kuala Lumpur City Escape',
        'title_ar'    => ar_pending(),
        'duration_en' => '4 Days / 3 Nights',
        'duration_ar' => '4 أيام / 3 ليالٍ',
        'cities_en'   => 'Kuala Lumpur',
        'cities_ar'   => 'كوالالمبور',
        'price_from'  => 'OMR 195',
        'intro_en'    => 'A fast-paced introduction to Malaysia\'s capital — soaring towers, street food and a day trip to the cool hills of Genting.',
        'highlights_en' => ['Petronas Towers', 'Batu Caves', 'KL city tour', 'Genting day trip'],
        'itinerary_en' => [
            ['title' => 'Arrival in Kuala Lumpur', 'desc' => 'Airport pickup and transfer to your hotel. Evening at leisure.'],
            ['title' => 'Kuala Lumpur City Tour', 'desc' => 'Petronas Towers, Merdeka Square, Batu Caves and Chinatown.'],
            ['title' => 'Genting Highlands', 'desc' => 'Full-day trip to the hill resort of Genting, including cable car ride.'],
            ['title' => 'Departure', 'desc' => 'Free morning for shopping, then transfer to the airport.'],
        ],
        'included_en' => ['Airport transfers', '3 nights hotel accommodation', 'Daily breakfast', 'KL city tour with guide', 'Genting Highlands day trip'],
        'excluded_en' => ['International flights', 'Travel insurance', 'Personal expenses', 'Meals not mentioned'],
        'image'       => 'assets/images/optimized/pkg-kl-city-escape',
        'gallery'     => [
            ['image' => 'assets/images/optimized/dest-kuala-lumpur', 'caption_en' => 'Kuala Lumpur'],
            ['image' => 'assets/images/optimized/exp-city-experiences', 'caption_en' => 'City Sightseeing'],
            ['image' => 'assets/images/optimized/exp-food-gastronomy', 'caption_en' => 'Local Cuisine'],
        ],
    ],
    [
        'slug'        => 'langkawi-island-retreat',
        'title_en'    => 'Langkawi Island Retreat',
        'title_ar'    => ar_pending(),
        'duration_en' => '4 Days / 3 Nights',
        'duration_ar' => '4 أيام / 3 ليالٍ',
        'cities_en'   => 'Langkawi',
        'cities_ar'   => 'لنكاوي',
        'price_from'  => 'OMR 225',
        'intro_en'    => 'Slow down on Malaysia\'s favourite island — cable cars over the rainforest, hopping between islets, and beach time in between.',
        'highlights_en' => ['Cable car & Sky Bridge', 'Island hopping', 'Beach resort stay', 'Duty-free shopping'],
        'itinerary_en' => [
            ['title' => 'Arrival in Langkawi', 'desc' => 'Airport pickup and check-in at your beach resort.'],
            ['title' => 'Langkawi Cable Car & Sky Bridge', 'desc' => 'Ride to the summit of Gunung Mat Cincang for panoramic views.'],
            ['title' => 'Island Hopping Tour', 'desc' => 'Boat trip to Pulau Dayang Bunting and surrounding islets.'],
            ['title' => 'Departure', 'desc' => 'Morning at leisure, then transfer to the airport.'],
        ],
        'included_en' => ['Airport transfers', '3 nights resort accommodation', 'Daily breakfast', 'Cable car tickets', 'Island hopping tour'],
        'excluded_en' => ['International flights', 'Travel insurance', 'Personal expenses', 'Meals not mentioned'],
        'image'       => 'assets/images/optimized/pkg-langkawi-retreat',
        'gallery'     => [
            ['image' => 'assets/images/optimized/dest-langkawi', 'caption_en' => 'Langkawi'],
            ['image' => 'assets/images/optimized/exp-beaches-islands', 'caption_en' => 'Beaches & Islands'],
            ['image' => 'assets/images/optimized/exp-adventure', 'caption_en' => 'Island Adventure'],
        ],
    ],
    [
        'slug'        => 'malaysia-highlights',
        'title_en'    => 'Malaysia Highlights',
        'title_ar'    => ar_pending(),
        'duration_en' => '6 Days / 5 Nights',
        'duration_ar' => '6 أيام / 5 ليالٍ',
        'cities_en'   => 'Kuala Lumpur · Genting · Malacca',
        'cities_ar'   => 'كوالالمبور · جنتنج · ملقا',
        'price_from'  => 'OMR 310',
        'intro_en'    => 'A well-paced overview of Peninsular Malaysia\'s best — city, hills and heritage in one itinerary.',
        'highlights_en' => ['Genting Highlands', 'Malacca heritage tour', 'City sightseeing', 'Local cuisine trail'],
        'itinerary_en' => [
            ['title' => 'Arrival in Kuala Lumpur', 'desc' => 'Airport pickup and transfer to your hotel.'],
            ['title' => 'Kuala Lumpur City Tour', 'desc' => 'Petronas Towers, Merdeka Square and Chinatown.'],
            ['title' => 'Genting Highlands', 'desc' => 'Day trip to the hill resort, cable car included.'],
            ['title' => 'Malacca Heritage Tour', 'desc' => 'Full-day excursion to the UNESCO-listed streets of Malacca.'],
            ['title' => 'Leisure Day in Kuala Lumpur', 'desc' => 'Free day for shopping or an optional excursion.'],
            ['title' => 'Departure', 'desc' => 'Transfer to the airport.'],
        ],
        'included_en' => ['Airport transfers', '5 nights hotel accommodation', 'Daily breakfast', 'KL & Malacca guided tours', 'Genting Highlands day trip'],
        'excluded_en' => ['International flights', 'Travel insurance', 'Personal expenses', 'Meals not mentioned'],
        'image'       => 'assets/images/optimized/pkg-malaysia-highlights',
        'gallery'     => [
            ['image' => 'assets/images/optimized/dest-kuala-lumpur', 'caption_en' => 'Kuala Lumpur'],
            ['image' => 'assets/images/optimized/dest-malacca', 'caption_en' => 'Malacca'],
            ['image' => 'assets/images/optimized/exp-culture-heritage', 'caption_en' => 'Culture & Heritage'],
        ],
    ],
    [
        'slug'        => 'kuala-lumpur-langkawi',
        'title_en'    => 'Kuala Lumpur + Langkawi',
        'title_ar'    => ar_pending(),
        'duration_en' => '6 Days / 5 Nights',
        'duration_ar' => '6 أيام / 5 ليالٍ',
        'cities_en'   => 'Kuala Lumpur · Langkawi',
        'cities_ar'   => 'كوالالمبور · لنكاوي',
        'price_from'  => 'OMR 355',
        'intro_en'    => 'The classic combination — city energy in Kuala Lumpur, then island calm in Langkawi.',
        'highlights_en' => ['City + island combo', 'Cable car experience', 'Beach relaxation', 'Flight transfers included'],
        'itinerary_en' => [
            ['title' => 'Arrival in Kuala Lumpur', 'desc' => 'Airport pickup and transfer to your hotel.'],
            ['title' => 'Kuala Lumpur City Tour', 'desc' => 'Petronas Towers, Batu Caves and city sightseeing.'],
            ['title' => 'Fly to Langkawi', 'desc' => 'Domestic flight to Langkawi and resort check-in.'],
            ['title' => 'Langkawi Cable Car & Sky Bridge', 'desc' => 'Panoramic views from Gunung Mat Cincang.'],
            ['title' => 'Island Hopping Tour', 'desc' => 'Boat excursion to nearby islets.'],
            ['title' => 'Departure', 'desc' => 'Transfer to Langkawi airport.'],
        ],
        'included_en' => ['Airport transfers', '5 nights accommodation', 'Daily breakfast', 'Domestic flight KL–Langkawi', 'Cable car & island hopping tour'],
        'excluded_en' => ['International flights', 'Travel insurance', 'Personal expenses', 'Meals not mentioned'],
        'image'       => 'assets/images/optimized/pkg-kl-langkawi',
        'gallery'     => [
            ['image' => 'assets/images/optimized/dest-kuala-lumpur', 'caption_en' => 'Kuala Lumpur'],
            ['image' => 'assets/images/optimized/dest-langkawi', 'caption_en' => 'Langkawi'],
            ['image' => 'assets/images/optimized/exp-beaches-islands', 'caption_en' => 'Island Hopping'],
        ],
    ],
    [
        'slug'        => 'family-malaysia',
        'title_en'    => 'Family Malaysia',
        'title_ar'    => ar_pending(),
        'duration_en' => '7 Days / 6 Nights',
        'duration_ar' => '7 أيام / 6 ليالٍ',
        'cities_en'   => 'Kuala Lumpur · Genting · Langkawi',
        'cities_ar'   => 'كوالالمبور · جنتنج · لنكاوي',
        'price_from'  => 'OMR 420',
        'intro_en'    => 'Theme parks, beaches and family-friendly stays — a week designed around travelling with children.',
        'highlights_en' => ['Theme parks', 'Family-friendly hotels', 'Island fun', 'Kid-friendly itinerary'],
        'itinerary_en' => [
            ['title' => 'Arrival in Kuala Lumpur', 'desc' => 'Airport pickup and hotel check-in.'],
            ['title' => 'Kuala Lumpur City Tour', 'desc' => 'Family-friendly sightseeing across the city.'],
            ['title' => 'Genting Highlands Theme Park', 'desc' => 'A full day of rides and cool mountain air.'],
            ['title' => 'Fly to Langkawi', 'desc' => 'Domestic flight and resort check-in.'],
            ['title' => 'Langkawi Family Day', 'desc' => 'Cable car, wildlife park and beach time.'],
            ['title' => 'Island Hopping Tour', 'desc' => 'A gentle boat trip suited to all ages.'],
            ['title' => 'Departure', 'desc' => 'Transfer to the airport.'],
        ],
        'included_en' => ['Airport transfers', '6 nights family accommodation', 'Daily breakfast', 'Domestic flight KL–Langkawi', 'Theme park & island hopping tickets'],
        'excluded_en' => ['International flights', 'Travel insurance', 'Personal expenses', 'Meals not mentioned'],
        'image'       => 'assets/images/optimized/pkg-family-malaysia',
        'gallery'     => [
            ['image' => 'assets/images/optimized/dest-kuala-lumpur', 'caption_en' => 'Kuala Lumpur'],
            ['image' => 'assets/images/optimized/dest-langkawi', 'caption_en' => 'Langkawi'],
            ['image' => 'assets/images/optimized/exp-adventure', 'caption_en' => 'Family Adventure'],
        ],
    ],
    [
        'slug'        => 'wonders-of-borneo',
        'title_en'    => 'Wonders of Borneo',
        'title_ar'    => ar_pending(),
        'duration_en' => '6 Days / 5 Nights',
        'duration_ar' => '6 أيام / 5 ليالٍ',
        'cities_en'   => 'Kota Kinabalu · Sandakan',
        'cities_ar'   => 'كوتا كينابالو · سندكان',
        'price_from'  => 'OMR 270',
        'intro_en'    => 'Venture into Sabah\'s wild side — orangutans, sun bears and proboscis monkeys along the Kinabatangan River, a rainforest canopy walkway, and the foothills of Mount Kinabalu.',
        'highlights_en' => ['Sepilok Orangutan Centre', 'Kinabatangan River cruises', 'Bornean Sun Bear Centre', 'Kinabalu Park & canopy walk'],
        'itinerary_en' => [
            ['title' => 'Arrival in Kota Kinabalu', 'desc' => 'Meet and greet at KKIA and transfer to your hotel. Evening at leisure. Overnight at Shangri-La Rasa Ria Resort.'],
            ['title' => 'Poring Hot Springs & Kinabalu Park', 'desc' => 'Scenic drive via Kundasang and Nabalu Market, the rainforest canopy walkway at Poring Hot Springs, and the Botanical Garden at Kinabalu Park, Malaysia\'s first UNESCO World Heritage Site. Overnight at Shangri-La Rasa Ria Resort.'],
            ['title' => 'Kota Kinabalu to Sandakan', 'desc' => 'Fly to Sandakan and visit the Sepilok Orangutan Rehabilitation Centre and the Bornean Sun Bear Conservation Centre, then transfer by road and boat to Bilit Rainforest Lodge on the Kinabatangan River for an evening wildlife cruise.'],
            ['title' => 'Kinabatangan River, Sandakan', 'desc' => 'Morning birdwatching cruise to Sukau Ox-Bow Lake and a visit to Bilit Village, followed by an afternoon and night river cruise spotting proboscis monkeys, orangutans, gibbons and pygmy elephants. Overnight at Bilit Rainforest Lodge.'],
            ['title' => 'Gomantong Cave to Sepilok', 'desc' => 'Boat and road transfer via Gomantong Cave, Sabah\'s largest limestone cave, before checking in to Sepilok Nature Resort for an afternoon at leisure.'],
            ['title' => 'Departure', 'desc' => 'Breakfast and check-out, then transfer to Sandakan Airport for your onward flight.'],
        ],
        'included_en' => ['Meet and greet services', 'Transfers and sightseeing in air-conditioned vehicles', 'English-speaking driver-guide and licensed tour guide', '5 nights\' accommodation (Shangri-La Rasa Ria Resort, Bilit Rainforest Lodge, Sepilok Nature Resort)', 'Daily breakfast and meals as listed in the itinerary', 'River cruises and entrance fees as per itinerary', 'Luggage portage for arrival and departure transfers', 'Sales and service tax'],
        'excluded_en' => ['Other personal expenses (soft drinks, laundry, etc.)', 'Midnight surcharge for services between 2200–0700 hrs', 'Entrance fees to places not stated in the itinerary', 'Meals and beverages not stated in the itinerary'],
        'image'       => 'assets/images/optimized/pkg-wonders-of-borneo',
        'gallery'     => [
            ['image' => 'assets/images/optimized/gal-sabah-1', 'caption_en' => 'Mount Kinabalu, Kinabalu Park'],
            ['image' => 'assets/images/optimized/dest-sabah', 'caption_en' => 'Sepilok Orangutan Rehabilitation Centre'],
            ['image' => 'assets/images/optimized/gal-borneo-sunbear', 'caption_en' => 'Bornean Sun Bear Conservation Centre'],
            ['image' => 'assets/images/optimized/gal-kuching-bako-1', 'caption_en' => 'Proboscis monkeys, Kinabatangan River'],
        ],
    ],
];
